apiVersion: apps/v1
kind: Deployment
metadata:
  name: jedonahoe
  labels:
    app: jedonahoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jedonahoe
  template:
    metadata:
      labels:
        app: jedonahoe
    spec:
      containers:
      - name: jedonahoe-app
        image: jdonahoe93/jedonahoe:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jedonahoe
spec:
  selector:
    app: jedonahoe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80